apiVersion: route.openshift.io/v1
kind: Route
metadata:
  name: nas-demo
  namespace: ipsec-nas-csi-demo
  labels:
    app: nas-demo
spec:
  to:
    kind: Service
    name: nas-demo
  port:
    targetPort: http
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: Redirect
