apiVersion: v1
kind: ConfigMap
metadata:
  name: ipsec-cert-sync-script
  namespace: {{ .Release.Namespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
data:
  sync.sh: |
{{ .Files.Get "files/sync.sh" | trimSuffix "\n" | indent 4 }}
