#!/usr/bin/env bash
# Generates the Perses dashboard from the Grafana one, so the two stay one dashboard:
#   charts/ipsec-nas/files/ipsec-nas.json  --percli migrate-->  scripts/perses-dashboard-fix.py
#     --> charts/ipsec-nas/files/ipsec-nas.perses.json            (the chart's PersesDashboard spec.config)
#     --> manifests/option-b-per-node-certs/33-perses-dashboard.yaml (the same, for the plain manifests)
#   and refreshes the Grafana ConfigMap of the plain manifests, manifests/option-b-per-node-certs/30-grafana-dashboard.yaml
# Then Option C's, from the same source:
#   charts/ipsec-nas/files/ipsec-nas.json  --scripts/option-c-dashboard.py-->  charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.json
#     --percli migrate--> scripts/perses-dashboard-fix.py --> charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.perses.json
# Run from the repository root after changing ipsec-nas.json:  scripts/perses-dashboard.sh
#
# Needs percli 0.54.0 (the Perses version in COO 1.5.2's go.mod; COO's server reports none) and its plugins UNPACKED; see
# https://github.com/ephico2real2/openshift-coo-helm/blob/main/docs/percli.md
#   PERCLI=percli  PERSES_PLUGINS=~/.local/share/perses/plugins
set -euo pipefail

PERCLI="${PERCLI:-percli}"
PLUGINS="${PERSES_PLUGINS:-${HOME}/.local/share/perses/plugins}"
GRAFANA=charts/ipsec-nas/files/ipsec-nas.json
CONFIG=charts/ipsec-nas/files/ipsec-nas.perses.json
MANIFEST=manifests/option-b-per-node-certs/33-perses-dashboard.yaml
GRAFANA_MANIFEST=manifests/option-b-per-node-certs/30-grafana-dashboard.yaml

command -v "${PERCLI}" >/dev/null || { echo "percli not found (set PERCLI)" >&2; exit 1; }
[[ -d "${PLUGINS}" ]] || { echo "no Perses plugins at ${PLUGINS} (set PERSES_PLUGINS to the unpacked plugins)" >&2; exit 1; }
ls "${PLUGINS}"/*.tar.gz >/dev/null 2>&1 && { echo "${PLUGINS} holds packed archives: percli needs them unpacked" >&2; exit 1; }

# percli 0.54.0 logs "failed query migration: no plugins found matching target" once per Grafana query and still
# converts every query (measured: all 27 expressions carried over verbatim). The fixer refuses placeholders.
"${PERCLI}" migrate -f "${GRAFANA}" --format native --plugin.path "${PLUGINS}" --use-default-datasource -o json \
  | python3 scripts/perses-dashboard-fix.py > "${CONFIG}.tmp"
mv "${CONFIG}.tmp" "${CONFIG}"

{
  cat <<'EOF'
# The Perses dashboard (Cluster Observability Operator 1.5 or later) and the datasource it queries.
# GENERATED by scripts/perses-dashboard.sh from charts/ipsec-nas/files/ipsec-nas.json: do not edit by hand.
# Viewers need cluster-monitoring-view (Thanos port 9091): docs/61-perses-dashboard-review.md, "Decision".
apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: ipsec-nas-thanos
  namespace: kcs-ipsec
  labels:
    app: ipsec-cert-sync
spec:
  client:
    tls:
      enable: true
      caCert:
        type: file
        certPath: /ca/service-ca.crt
  config:
    display:
      name: OpenShift Thanos (cluster)
    default: false
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
            # the Perses secret COO derives from spec.client.tls; the proxy must name it
            secret: ipsec-nas-thanos-secret
---
apiVersion: perses.dev/v1alpha2
kind: PersesDashboard
metadata:
  name: ipsec-nas
  namespace: kcs-ipsec
  labels:
    app: ipsec-cert-sync
spec:
  config:
EOF
  sed 's/^/    /' "${CONFIG}"
} > "${MANIFEST}"

# The Grafana ConfigMap keeps its header and embeds the Grafana JSON verbatim under "ipsec-nas.json: |".
{
  sed '/^  ipsec-nas.json: |$/q' "${GRAFANA_MANIFEST}"
  sed 's/^/    /' "${GRAFANA}"
} > "${GRAFANA_MANIFEST}.tmp"
grep -q '^  ipsec-nas.json: |$' "${GRAFANA_MANIFEST}.tmp" || { echo "${GRAFANA_MANIFEST}: no 'ipsec-nas.json: |' key" >&2; rm -f "${GRAFANA_MANIFEST}.tmp"; exit 1; }
mv "${GRAFANA_MANIFEST}.tmp" "${GRAFANA_MANIFEST}"
echo "wrote ${CONFIG}, ${MANIFEST} and ${GRAFANA_MANIFEST}"

# Option C: the same dashboard, naming its own uid, title and reporting pod (ipsec-nas-metrics).
C_GRAFANA=charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.json
C_CONFIG=charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.perses.json
python3 scripts/option-c-dashboard.py < "${GRAFANA}" > "${C_GRAFANA}.tmp"
mv "${C_GRAFANA}.tmp" "${C_GRAFANA}"
"${PERCLI}" migrate -f "${C_GRAFANA}" --format native --plugin.path "${PLUGINS}" --use-default-datasource -o json \
  | REPORTING_POD=ipsec-nas-metrics python3 scripts/perses-dashboard-fix.py > "${C_CONFIG}.tmp"
mv "${C_CONFIG}.tmp" "${C_CONFIG}"
echo "wrote ${C_GRAFANA} and ${C_CONFIG}"
