#!/usr/bin/env bash
# Generates the Perses dashboard from the Grafana one, so the two stay one dashboard:
#   charts/ipsec-nas/files/ipsec-nas.json  --perses-dashboard-->
#         charts/ipsec-nas/files/ipsec-nas.perses.json               (the chart's PersesDashboard spec.config)
#     --> manifests/option-b-per-node-certs/33-perses-dashboard.yaml (the same, for the plain manifests)
#   and refreshes the Grafana ConfigMap of the plain manifests, manifests/option-b-per-node-certs/30-grafana-dashboard.yaml
# Then Option C's, from the same source:
#   charts/ipsec-nas/files/ipsec-nas.json  --scripts/option-c-dashboard.py-->  charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.json
#     --perses-dashboard--> charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.perses.json
# Run from the repository root after changing ipsec-nas.json:  scripts/perses-dashboard.sh
#
# The Grafana JSON is the only source: whatever the Perses dashboard shows is written there. The conversion is
# diagram-kit's perses-dashboard (https://github.com/ephico2real2/diagram-kit, MPL-2.0; v0.2.1 or later). It runs
# percli migrate, names the datasource on every query and on the Node filter, and refuses a panel that became a
# placeholder or a query that differs from the Grafana one: docs/61-perses-dashboard-review.md, "Change the dashboard".
# Install it once:
#   python3 -m venv .venv && .venv/bin/pip install "diagram-kit @ git+https://github.com/ephico2real2/diagram-kit@v0.2.3"
# It is taken from PERSES_DASHBOARD, from the PATH, or from .venv/bin. percli must be 0.54.0, the Perses version in
# COO 1.5.2's go.mod (COO's server reports none). By default it runs from the Perses image, with podman or docker:
#   PERSES_IMAGE=docker.io/persesdev/perses:v0.54.0
# Without a container engine, name a percli binary and its UNPACKED plugins
# (https://github.com/ephico2real2/openshift-coo-helm/blob/main/docs/percli.md):
#   PERCLI=percli  PERSES_PLUGINS=~/.local/share/perses/plugins
set -euo pipefail

IMAGE="${PERSES_IMAGE:-docker.io/persesdev/perses:v0.54.0}"
DATASOURCE=ipsec-nas-thanos   # the PersesDatasource each chart creates beside its dashboard
GRAFANA=charts/ipsec-nas/files/ipsec-nas.json
CONFIG=charts/ipsec-nas/files/ipsec-nas.perses.json
MANIFEST=manifests/option-b-per-node-certs/33-perses-dashboard.yaml
GRAFANA_MANIFEST=manifests/option-b-per-node-certs/30-grafana-dashboard.yaml
# Option C: the same dashboard, naming its own uid, title and reporting pod (ipsec-nas-metrics).
C_GRAFANA=charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.json
C_CONFIG=charts/ipsec-nas-option-c-metrics/files/ipsec-nas-option-c.perses.json
# All five files are made beside their targets, as <target>.tmp, and moved into place together at the very end:
# when a check or a step fails, no file of the repository has changed and no .tmp is left.
TARGETS=("${CONFIG}" "${MANIFEST}" "${GRAFANA_MANIFEST}" "${C_GRAFANA}" "${C_CONFIG}")
trap 'for f in "${TARGETS[@]}"; do rm -f "${f}.tmp"; done' EXIT

# PERSES_DASHBOARD is a path or the name of a command; without it the PATH is searched, then .venv/bin.
CONVERT="$(command -v "${PERSES_DASHBOARD:-perses-dashboard}" || true)"
[[ -n "${CONVERT}" || -n "${PERSES_DASHBOARD:-}" ]] || CONVERT=.venv/bin/perses-dashboard
[[ -x "${CONVERT}" ]] || { echo "perses-dashboard not found: install diagram-kit (see the top of this script) or set PERSES_DASHBOARD" >&2; exit 1; }

# convert <grafana.json> <perses.json>: nothing is written when a check fails. The kit says "wrote <file> (24 panels)";
# the file it is handed here is the target's .tmp, so its line is shown with the target's name.
convert() {
  if [[ -n "${PERCLI:-}" ]]; then
    "${CONVERT}" "$1" "$2" --datasource "${DATASOURCE}" --percli "${PERCLI}" \
      --plugins "${PERSES_PLUGINS:-${HOME}/.local/share/perses/plugins}"
  else
    "${CONVERT}" "$1" "$2" --datasource "${DATASOURCE}" --image "${IMAGE}"
  fi | sed 's/\.tmp (/ (/'
}

convert "${GRAFANA}" "${CONFIG}.tmp"

{
  cat <<'EOF'
# The Perses dashboard (Cluster Observability Operator 1.5 or later) and the datasource it queries.
# GENERATED by scripts/perses-dashboard.sh from charts/ipsec-nas/files/ipsec-nas.json: do not edit by hand.
# Viewers need cluster-monitoring-view (Thanos port 9091): docs/61-perses-dashboard-review.md, "Decision".
apiVersion: perses.dev/v1alpha2
kind: PersesDatasource
metadata:
  name: ipsec-nas-thanos
  namespace: kcs-ipsec
  labels:
    app: ipsec-cert-sync
spec:
  client:
    tls:
      enable: true
      caCert:
        type: file
        certPath: /ca/service-ca.crt
  config:
    display:
      name: OpenShift Thanos (cluster)
    default: false
    plugin:
      kind: PrometheusDatasource
      spec:
        proxy:
          kind: HTTPProxy
          spec:
            url: https://thanos-querier.openshift-monitoring.svc.cluster.local:9091
            # the Perses secret COO derives from spec.client.tls; the proxy must name it
            secret: ipsec-nas-thanos-secret
---
apiVersion: perses.dev/v1alpha2
kind: PersesDashboard
metadata:
  name: ipsec-nas
  namespace: kcs-ipsec
  labels:
    app: ipsec-cert-sync
spec:
  config:
EOF
  sed 's/^/    /' "${CONFIG}.tmp"
} > "${MANIFEST}.tmp"

# The Grafana ConfigMap keeps its header and embeds the Grafana JSON verbatim under "ipsec-nas.json: |".
{
  sed '/^  ipsec-nas.json: |$/q' "${GRAFANA_MANIFEST}"
  sed 's/^/    /' "${GRAFANA}"
} > "${GRAFANA_MANIFEST}.tmp"
grep -q '^  ipsec-nas.json: |$' "${GRAFANA_MANIFEST}.tmp" || { echo "${GRAFANA_MANIFEST}: no 'ipsec-nas.json: |' key" >&2; exit 1; }

python3 scripts/option-c-dashboard.py < "${GRAFANA}" > "${C_GRAFANA}.tmp"
convert "${C_GRAFANA}.tmp" "${C_CONFIG}.tmp"

for f in "${TARGETS[@]}"; do mv "${f}.tmp" "${f}"; done
echo "wrote ${CONFIG}, ${MANIFEST} and ${GRAFANA_MANIFEST}"
echo "wrote ${C_GRAFANA} and ${C_CONFIG}"
